# frozen_string_literal: true

# == Schema Information
#
# Table name: calculators
#
#  id              :integer          not null, primary key
#  type            :string
#  calculable_type :string
#  calculable_id   :bigint
#  settings        :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_calculators_on_calculable_type_and_calculable_id  (calculable_type,calculable_id)
#  index_calculators_on_id_and_type                        (id,type)
#
class Calculator < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  include StoreEnhanceableConcern
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :calculable, polymorphic: true, optional: true, inverse_of: :calculator
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
