# == Schema Information
#
# Table name: promotion_rules
#
#  id           :integer          not null, primary key
#  type         :string
#  promotion_id :integer
#  product_id   :integer
#  settings     :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_promotion_rules_on_product_id    (product_id)
#  index_promotion_rules_on_promotion_id  (promotion_id)
#
class PromotionRule < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  include StoreEnhanceableConcern
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :promotion
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def pass_rule?(order)
    raise "Not Implement Error!"
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
